### ISSUE TITLE
@xmly别人是装不到的  建议采用插件形式  不要单独搞一个包出来

### ISSUE THREAD

**Issue by TangShengda** [nanhaishiyounan/styled-components#1]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by nanhaishiyounan** [comment]
公司内用就行，插件还得改已有代码，低版本styled不支持插件吧
